### ISSUE TITLE
Missing Bullet points 

### ISSUE THREAD

**Issue by elenafranck** [chrismsimpson/Metropolis#27] opened 2018-10-11 17:52 UTC
Hi Chris, 

@chrismsimpson I would really appreciate it if you'd consider adding bullet points to this glyph set. A simple circle or square would really go a long way in this typeface's usability for my purposes. Thanks!!

**Comment by sdurnov** [comment] 2018-12-25 21:14
Duplicate of https://github.com/chrismsimpson/Metropolis/issues/10

**Comment by chrismsimpson** [comment] 2020-02-01 23:46
Circle bullet is in there :)

**Closed by chrismsimpson** 2020-02-01 23:46 UTC
